[project]
name = "pythonproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "h2>=4.2.0",
    "httpx>=0.28.1",
    "requests>=2.32.4",
]
